# Generated by Django 5.2.7 on 2025-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_vendor',
            field=models.BooleanField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
